# cursor
#cursor_size=24
cursor_hide_timeout=3


xwayland_persistence=0 # Keep XWayland running even when no X11 apps are open (reduces startup lag).
single_scratchpad=1 # show one scratchpad window at a time
scratchpad_cross_monitor=1 # share the scratchpad across monitors
