# Sub-config loader
# This file sources smaller configuration files for clarity.

# env VARS
# ---------- Themes ----------
env = QT_QPA_PLATFORM, wayland
#env=QT_QPA_PLATFORM,Wayland;xcb
env = QT_QPA_PLATFORMTHEME,qt5ct
#env=QT_WAYLAND_FORCE_DPI,140
env = QT_WAYLAND_DISABLE_WINDOWDECORATION,1
env = QT_AUTO_SCREEN_SCALE_FACTOR,1
#env=GLFW_IM_MODULE,ibus

# ---------- Input Method ----------
env = QT_IM_MODULE, fcitx
env = XMODIFIERS, @im=fcitx
env = SDL_IM_MODULE, fcitx
env = INPUT_METHOD, fcitx

# ---------- Cursor Size ----------
env = XCURSOR_SIZE, 24


source=./rules.conf
source=./input.conf
source=./layout.conf
source=./binds.conf
source=./misc.conf


exec-once=~/.config/mango/autostart.sh
