# █░█░█ █ █▄░█ █▀▄ █▀█ █░█░█   █▀█ █░█ █░░ █▀▀ █▀
# ▀▄▀▄▀ █ █░▀█ █▄▀ █▄█ ▀▄▀▄▀   █▀▄ █▄█ █▄▄ ██▄ ▄█

# Floating
windowrule {
  name = "Floating window apps"
  match:class = ^(blueberry\.py|org\.pulseaudio\.pavucontrol|com\.network\.manager)$

  float = true
}


# Picture-in-Picture
windowrule = tag +picture-in-picture, match:title ^([Pp]icture[-\s]?[Ii]n[-\s]?[Pp]icture)(.*)$
windowrule = float true, match:tag picture-in-picture
windowrule = keep_aspect_ratio false, match:tag picture-in-picture
windowrule = move 90% 90%, match:tag picture-in-picture
windowrule = size 10% 10%, match:tag picture-in-picture
windowrule = pin true, match:tag picture-in-picture


# Dialog windows – float these windows.
windowrule = float true, match:title ^(Open File)$
windowrule = float true, match:title ^(Select a File)$
windowrule = float true, match:title ^(Open Folder)$
windowrule = float true, match:title ^(Save As)$
windowrule = float true, match:title ^(Library)$
windowrule = float true, match:title ^(File Upload)$

# Add size rules
windowrule = size 60% 70%, match:title ^(Open File)$
windowrule = size 60% 70%, match:title ^(Select a File)$
windowrule = size 60% 70%, match:title ^(Open Folder)$
windowrule = size 60% 70%, match:title ^(Save As)$
windowrule = size 60% 70%, match:title ^(Library)$
windowrule = size 60% 70%, match:title ^(File Upload)$
windowrule = size 80% 60%, match:title ^(Bluetooth)$ 

# idle_inhibit rules
windowrule = idle_inhibit  true,  match:fullscreen match:class ^(.*mpv.*)$|^(.*vlc.*)$


# █░░ ▄▀█ █▄█ █▀▀ █▀█   █▀█ █░█ █░░ █▀▀ █▀
# █▄▄ █▀█ ░█░ ██▄ █▀▄   █▀▄ █▄█ █▄▄ ██▄ ▄█

layerrule = blur 1,match:namespace rofi
layerrule = ignore_alpha 0,match:namespace rofi
layerrule = blur 1,match:namespace notifications
layerrule = ignore_alpha 0,match:namespace notifications
layerrule = blur 1,match:namespace swaync-notification-window
layerrule = ignore_alpha 0,match:namespace swaync-notification-window
layerrule = blur true,match:namespace swaync-control-center
layerrule = ignore_alpha 0,match:namespace swaync-control-center
layerrule = blur 1, xray 1, match:namespace logout_dialog


### WINDOWS AND WORKSPACES ###
##############################

# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more
# See https://wiki.hyprland.org/Configuring/Workspace-Rules/ for workspace rules


# app Workspace assignments

windowrule = workspace 1, match:class google-chrome
windowrule = workspace 1, match:class zen
windowrule = workspace 1, match:class Chromium
windowrule = workspace 2, match:class Code
windowrule = workspace 3, match:class md.obsidian.Obsidian
windowrule = workspace 3, match:class com.github.th_ch.youtube_music
windowrule = workspace 3, match:class mpv
windowrule = workspace 3, match:class vlc
windowrule = workspace 4, match:class org.gnome.Nautilus
windowrule = match:class com.mitchellh.ghostty, workspace 2, no_blur true


