
workspace=1,monitor:DP-4,default:true,layout:scrolling
workspace=2,monitor:DP-4
workspace=3,monitor:DP-4,layout:scrolling
workspace=4,monitor:DP-4,layout:scrolling
workspace=5,monitor:DP-4,layout:scrolling
workspace=6,monitor:DP-4,layout:scrolling
workspace=7,monitor:DP-4,layout:scrolling
workspace=8,monitor:DP-4,layout:scrolling
workspace=9,monitor:eDP-1,default:true,layout:scrolling
workspace=10,monitor:eDP-1,layout:scrolling
