hl.workspace_rule({ workspace = "1", monitor = "DP-4", default = true, layout = "scrolling" })
hl.workspace_rule({ workspace = "2", monitor = "DP-4" })
hl.workspace_rule({ workspace = "3", monitor = "DP-4", layout = "scrolling" })
hl.workspace_rule({ workspace = "4", monitor = "DP-4", layout = "scrolling" })
hl.workspace_rule({ workspace = "5", monitor = "DP-4", layout = "scrolling" })
hl.workspace_rule({ workspace = "6", monitor = "DP-4", layout = "scrolling" })
hl.workspace_rule({ workspace = "7", monitor = "DP-4", layout = "scrolling" })
hl.workspace_rule({ workspace = "8", monitor = "DP-4", layout = "scrolling" })
hl.workspace_rule({ workspace = "9", monitor = "eDP-1", default = true, layout = "scrolling" })
hl.workspace_rule({ workspace = "10", monitor = "eDP-1", layout = "scrolling" })